//
//  KeyValue.swift
//  Music
//
//  Created by Gary Davies on 22/11/18.
//  Copyright © 2018 Gary Davies. All rights reserved.
//

import Foundation

open class KeyValue {
    
    // MARK: - Keys
    
    open static let errorKey = "error"
    open static let methodKey = "method"
    open static let urlKey = "url"
    open static let statusCodeKey = "statusCode"
    open static let contentKey = "content"
    open static let protocolKey = "protocol"
    open static let domainKey = "domain"
    open static let apiRelKey = "apiRel"
    open static let apiVersionKey = "apiVersion"
    open static let relKey = "rel"
    open static let authorizationKey = "authorization"
    open static let limitKey = "limit"
    open static let offsetKey = "offset"
    open static let requestParametersKey = "requestParameters"
    open static let dictionaryKey = "dictionary"
    open static let screenWidthKey = "screenWidth"
    open static let screenHeightKey = "screenHeight"
    open static let deviceIdKey = "deviceId"
    open static let modelKey = "model"
    open static let operatingSystemNameKey = "operatingSystemName"
    open static let operatingSystemVersionKey = "operatingSystemVersion"
    open static let dataKey = "data"
    open static let typeKey = "type"
    open static let idKey = "id"
    open static let authTokenKey = "authToken"
    open static let apiKey = "api"
    open static let responseContentTypeKey = "responseContentType"
    open static let resultsKey = "results"
    open static let nameKey = "name"
    open static let latKey = "lat"
    open static let longKey = "long"
    open static let mineKey = "mine"
    open static let schemasKey = "schemas"
    open static let versionKey = "version"
    open static let definitionKey = "definition"
    open static let definitionsKey = "definitions"
    open static let propertiesKey = "properties"
    open static let speciesKey = "species"
    open static let enumKey = "enum"
    open static let trainedKey = "trained"
    open static let userKey = "user"
    open static let projectKey = "project"
    open static let surveyKey = "survey"
    open static let observationKey = "observation"
    open static let dateTimeKey = "datetime"
    open static let trackKey = "track"
    open static let serverIdKey = "_id"
    open static let recordKey = "record"
    open static let schemaKey = "schema"
    open static let locationKey = "location"
    open static let mediaKey = "media"
    open static let fileNameKey = "fileName"
    open static let orderKey = "order"
    open static let requiredKey = "required"
    open static let sightingTimeKey = "sightingTime"
    open static let behaviourKey = "behaviour"
    open static let behaviourOtherKey = "behaviourOther"
    open static let behaviourFeedingOnKey = "behaviourFeedingOn"
    open static let feedingOnKey = "feedingOn"
    open static let behaviourFeedingOther = "behaviourFeedingOther"
    open static let notesKey = "notes"
    open static let landUseKey = "landUse"
    open static let landUseOtherKey = "landUseOther"
    open static let numberSeenKey = "numberSeen"
    open static let lowKey = "low"
    open static let bestKey = "best"
    open static let highKey = "high"
    open static let parentKey = "_parent"
    open static let childrenKey = "_children"
    open static let defaultKey = "default"
    open static let buttonKey = "button"
    open static let checkboxKey = "checkbox"
    open static let descriptionLabelKey = "descriptionLabel"
    open static let schemaValueKey = "schemaValue"
    open static let otherKey = "other"
    open static let observationIdKey = "observationId"
    open static let uploadedKey = "uploaded"
    open static let descriptionKey = "description"
    open static let labelNumberOfLinesKey = "labelNumberOfLines"
    open static let labelVerticalPositionKey = "labelVerticalPosition"
    open static let checkboxVerticalPositionKey = "checkboxVerticalPosition"
    open static let accuracyKey = "accuracy"
    
    // MARK: - Values
        
    open static let documentsValue = "documents"
    open static let bundleValue = "bundle"
    open static let getValue = "get"
    open static let postValue = "post"
    open static let emptyStringValue = ""
    open static let deviceTypeValue = "device"
    open static let dictionaryValue = "dictionary"
    open static let observationValue = "observation"
    open static let surveyValue = "survey"
    open static let otherValue = "Other"
    open static let itsAGroup = "It's a group"
    
}
